apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-app
          image: DOCKERHUB_USER/inventory-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: inventory-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: INVENTORY_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INVENTORY_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INVENTORY_DB_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  namespace: orchestrator
spec:
  selector:
    app: inventory-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
