      containers:
      - name: api-gateway
        image: nocrarii/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: INVENTORY_SERVICE_URL
          value: "http://inventory-app.microservices.svc.cluster.local:8080"
        - name: BILLING_SERVICE_URL
          value: "http://billing-app.microservices.svc.cluster.local:8080"
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Démarrage: juste vérifier que le process écoute
        startupProbe:
          tcpSocket: { port: 3000 }
          failureThreshold: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
