apiVersion: v1
kind: Service
metadata:
  name: billing-app
  namespace: microservices
spec:
  selector:
    app: billing-app
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: None  # Headless service for StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
  namespace: microservices
spec:
  serviceName: billing-app
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
        - name: billing-app
          image: nocrarii/billing-app:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: BILLING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-user
            - name: BILLING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
            - name: BILLING_DB_NAME
              value: "billing"
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-password
            - name: RABBITMQ_QUEUE
              value: "billing_queue"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
