apiVersion: v1
kind: Service
metadata:
  name: inventory-app
  namespace: microservices
spec:
  selector:
    app: inventory-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      initContainers:
        - name: wait-db
          image: postgres:14-alpine
          env:
            - name: PGHOST
              value: "inventory-db-0.inventory-db.microservices.svc.cluster.local"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-user
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Waiting for Postgres at ${PGHOST}:${PGPORT} ..."
              for i in $(seq 1 60); do
                if pg_isready -h "${PGHOST}" -p "${PGPORT}" -U "${PGUSER}"; then
                  echo "Postgres is ready"; exit 0
                fi
                echo "not ready ($i)"; sleep 2
              done
              echo "Postgres not ready after wait"; exit 1
      containers:
        - name: inventory-app
          image: nocrarii/inventory-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: INVENTORY_APP_PORT
              value: "8080"
            - name: INVENTORY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-user
            - name: INVENTORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
            - name: INVENTORY_DB_NAME
              value: "inventory"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"