apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  INVENTORY_DB_HOST: "inventory-db"
  INVENTORY_DB_PORT: "5432"
  INVENTORY_DB_NAME: "inventory"
  BILLING_DB_HOST: "billing-db"
  BILLING_DB_PORT: "5432"
  BILLING_DB_NAME: "billing"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "billing_queue"
  API_GATEWAY_PORT: "3000"
  APP_PORT: "8080"