apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-pv
  namespace: microservices
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/inventory-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage

---