apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: orchestrator
data:
  INVENTORY_DB_NAME: inventory
  BILLING_DB_NAME: orders
  RABBITMQ_QUEUE: orders
  API_GATEWAY_PORT: "3000"
  INVENTORY_APP_PORT: "8080"
  BILLING_APP_PORT: "8080"
