apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-db-init
  namespace: orchestrator
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS movies (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT NOW()
    );
