apiVersion: v1
kind: Service
metadata:
  name: billing-app
  namespace: orchestrator
spec:
  clusterIP: None
  selector:
    app: billing-app
  ports:
    - port: 8080
      name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
  namespace: orchestrator
spec:
  serviceName: billing-app
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
        - name: billing-app
          image: DOCKERHUB_USER/billing-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq-svc:5672
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_QUEUE
            - name: DB_HOST
              value: billing-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BILLING_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BILLING_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BILLING_DB_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
