apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: microservices
type: Opaque
data:
  # admin / rabbitmq123
  rabbitmq-user: YWRtaW4=
  rabbitmq-password: cmFiYml0bXExMjM=
  rabbitmq-erlang-cookie: U1VQRVJTRUNSRVRDT09LSUU=